server:
  port: ${SERVER_PORT:5610}


spring:
  main:
    allow-circular-references: true
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"
  devtools:
    restart:
      enabled: false